use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

use crate::scanner::Finding;

// ── Rich vulnerability context accumulated across agents ──

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct VulnContext {
    pub file_context: FileContext,
    pub dataflow: DataflowTrace,
    pub exploit_assessment: ExploitAssessment,
    pub agent_trace: Vec<AgentStep>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct FileContext {
    pub language: String,
    pub is_test_file: bool,
    pub is_generated: bool,
    pub imports: Vec<String>,
    pub function_signature: String,
    pub function_body_snippet: String,
    pub callers: Vec<String>,
    pub related_files: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct DataflowTrace {
    pub sources: Vec<DataflowNode>,
    pub sanitizers: Vec<DataflowNode>,
    pub sinks: Vec<DataflowNode>,
    pub taint_path: Vec<String>,
    pub is_user_controlled: bool,
    pub has_sanitization: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataflowNode {
    pub kind: String,
    pub expression: String,
    pub file: String,
    pub line: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ExploitAssessment {
    pub is_exploitable: bool,
    pub attack_vector: String,
    pub prerequisites: Vec<String>,
    pub impact: String,
    pub cvss_estimate: Option<f32>,
    pub poc_sketch: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentStep {
    pub agent: String,
    pub action: String,
    pub result_summary: String,
}

// ── Analysis strategy per finding category ──

#[derive(Debug, Clone, Copy)]
pub enum AnalysisStrategy {
    SecretTriage,
    VulnDeepDive,
    TaintTrace,
}

impl AnalysisStrategy {
    pub fn from_rule_id(rule_id: &str) -> Self {
        if rule_id.starts_with("SEC") {
            Self::SecretTriage
        } else if rule_id.starts_with("TAINT") {
            Self::TaintTrace
        } else {
            Self::VulnDeepDive
        }
    }

    pub fn required_agents(&self) -> &[AgentRole] {
        match self {
            Self::SecretTriage => &[AgentRole::ContextGatherer, AgentRole::Synthesizer],
            Self::VulnDeepDive => &[
                AgentRole::ContextGatherer,
                AgentRole::DataflowTracer,
                AgentRole::ExploitValidator,
                AgentRole::Synthesizer,
            ],
            Self::TaintTrace => &[
                AgentRole::ContextGatherer,
                AgentRole::DataflowTracer,
                AgentRole::Synthesizer,
            ],
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub enum AgentRole {
    ContextGatherer,
    DataflowTracer,
    ExploitValidator,
    Synthesizer,
}


// ── Static context gathering (no LLM needed) ──

pub fn gather_static_context(
    finding: &Finding,
    file_contents: &HashMap<PathBuf, String>,
) -> FileContext {
    let content = file_contents
        .get(&finding.file_path)
        .map(|s| s.as_str())
        .unwrap_or("");

    let lines: Vec<&str> = content.lines().collect();
    let file_name = finding.file_path.file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("");

    let ext = finding.file_path.extension()
        .and_then(|e| e.to_str())
        .unwrap_or("");

    let language = match ext {
        "py" => "Python",
        "js" | "jsx" => "JavaScript",
        "ts" | "tsx" => "TypeScript",
        "java" => "Java",
        "go" => "Go",
        "rs" => "Rust",
        "rb" => "Ruby",
        "php" => "PHP",
        _ => "Unknown",
    }.to_string();

    let is_test_file = file_name.starts_with("test_")
        || file_name.ends_with("_test.py")
        || file_name.ends_with("_test.go")
        || file_name.ends_with(".test.js")
        || file_name.ends_with(".test.ts")
        || file_name.ends_with("_spec.rb")
        || file_name.contains("fixture")
        || file_name.contains("mock")
        || finding.file_path.components().any(|c| {
            let s = c.as_os_str().to_str().unwrap_or("");
            s == "test" || s == "tests" || s == "__tests__" || s == "spec" || s == "fixtures"
        });

    let is_generated = lines.iter().take(5).any(|l| {
        let lower = l.to_lowercase();
        lower.contains("auto-generated") || lower.contains("do not edit")
            || lower.contains("generated by") || lower.contains("autogenerated")
    });

    let imports: Vec<String> = lines.iter()
        .filter(|l| {
            let trimmed = l.trim();
            trimmed.starts_with("import ")
                || trimmed.starts_with("from ")
                || trimmed.starts_with("use ")
                || trimmed.starts_with("require(")
                || trimmed.starts_with("const ") && trimmed.contains("require(")
                || trimmed.starts_with("#include")
        })
        .take(20)
        .map(|l| l.trim().to_string())
        .collect();

    let (func_sig, func_body) = extract_enclosing_function(&lines, finding.line_number, ext);

    let callers = find_callers_of_function(&func_sig, file_contents, &finding.file_path);

    FileContext {
        language,
        is_test_file,
        is_generated,
        imports,
        function_signature: func_sig,
        function_body_snippet: func_body,
        callers,
        related_files: Vec::new(),
    }
}

fn extract_enclosing_function(lines: &[&str], target_line: usize, ext: &str) -> (String, String) {
    if target_line == 0 || lines.is_empty() {
        return (String::new(), String::new());
    }

    let idx = (target_line - 1).min(lines.len() - 1);

    let func_patterns: &[&str] = match ext {
        "py" => &["def ", "async def "],
        "js" | "jsx" | "ts" | "tsx" => &["function ", "async function ", "const ", "=> {"],
        "java" => &["public ", "private ", "protected ", "static ", "void "],
        "go" => &["func "],
        "rs" => &["fn ", "pub fn ", "pub async fn ", "async fn "],
        _ => &["function ", "def ", "fn "],
    };

    let mut func_start = idx;
    for i in (0..=idx).rev() {
        let trimmed = lines[i].trim();
        if func_patterns.iter().any(|p| trimmed.contains(p)) {
            func_start = i;
            break;
        }
    }

    let signature = lines[func_start].trim().to_string();

    let body_start = func_start;
    let body_end = (func_start + 30).min(lines.len());
    let body: String = lines[body_start..body_end]
        .iter()
        .enumerate()
        .map(|(i, l)| format!("{:>4} | {}", body_start + i + 1, l))
        .collect::<Vec<_>>()
        .join("\n");

    (signature, body)
}

fn find_callers_of_function(
    func_sig: &str,
    file_contents: &HashMap<PathBuf, String>,
    current_file: &PathBuf,
) -> Vec<String> {
    let func_name = func_sig.split('(').next()
        .unwrap_or("")
        .split_whitespace()
        .last()
        .unwrap_or("");

    if func_name.is_empty() || func_name.len() < 3 {
        return Vec::new();
    }

    let mut callers = Vec::new();

    for (path, content) in file_contents {
        if path == current_file {
            continue;
        }
        for (line_num, line) in content.lines().enumerate() {
            if line.contains(func_name) && line.contains('(') {
                callers.push(format!("{}:{} — {}", path.display(), line_num + 1, line.trim()));
                if callers.len() >= 5 {
                    return callers;
                }
            }
        }
    }

    callers
}

// ── Static dataflow analysis (no LLM needed) ──

pub fn trace_static_dataflow(
    finding: &Finding,
    file_contents: &HashMap<PathBuf, String>,
    file_ctx: &FileContext,
) -> DataflowTrace {
    let content = file_contents
        .get(&finding.file_path)
        .map(|s| s.as_str())
        .unwrap_or("");

    let lines: Vec<&str> = content.lines().collect();
    let lang = file_ctx.language.as_str();

    let sources = find_sources(&lines, lang);
    let sanitizers = find_sanitizers(&lines, lang);
    let sinks = find_sinks(&lines, lang, &finding.file_path);

    let is_user_controlled = !sources.is_empty();
    let has_sanitization = !sanitizers.is_empty();

    let taint_path = build_taint_path(&sources, &sanitizers, &sinks);

    DataflowTrace {
        sources,
        sanitizers,
        sinks,
        taint_path,
        is_user_controlled,
        has_sanitization,
    }
}

fn find_sources(lines: &[&str], lang: &str) -> Vec<DataflowNode> {
    let source_patterns: Vec<&str> = match lang {
        "Python" => vec![
            "request.args", "request.form", "request.json", "request.data",
            "request.GET", "request.POST", "input(", "sys.argv",
            "os.environ", "flask.request",
        ],
        "JavaScript" | "TypeScript" => vec![
            "req.body", "req.query", "req.params", "req.headers",
            "document.location", "window.location", "document.URL",
            "document.cookie", "localStorage", "process.argv",
        ],
        "Java" => vec![
            "getParameter(", "getHeader(", "getInputStream(",
            "getReader(", "getCookies(", "getQueryString(",
        ],
        "Go" => vec![
            "r.URL.Query(", "r.FormValue(", "r.Body",
            "r.Header.Get(", "os.Args",
        ],
        _ => vec!["input", "argv", "stdin", "request"],
    };

    let mut nodes = Vec::new();
    for (i, line) in lines.iter().enumerate() {
        for pat in &source_patterns {
            if line.contains(pat) {
                nodes.push(DataflowNode {
                    kind: "source".to_string(),
                    expression: line.trim().to_string(),
                    file: String::new(),
                    line: i + 1,
                });
                break;
            }
        }
    }
    nodes.truncate(10);
    nodes
}

fn find_sanitizers(lines: &[&str], lang: &str) -> Vec<DataflowNode> {
    let sanitizer_patterns: Vec<&str> = match lang {
        "Python" => vec![
            "escape(", "quote(", "sanitize(", "clean(",
            "bleach.", "markupsafe.", "html.escape(",
            "parameterized", "prepared", "%s", "?",
        ],
        "JavaScript" | "TypeScript" => vec![
            "escape(", "sanitize(", "encodeURI(", "encodeURIComponent(",
            "DOMPurify", "xss(", "validator.", "helmet",
        ],
        "Java" => vec![
            "PreparedStatement", "setString(", "setInt(",
            "ESAPI", "encode(", "sanitize(", "Encoder",
        ],
        "Go" => vec![
            "html.EscapeString(", "template.HTML(",
            "url.QueryEscape(", "Prepare(",
        ],
        _ => vec!["escape", "sanitize", "encode", "prepared", "parameterize"],
    };

    let mut nodes = Vec::new();
    for (i, line) in lines.iter().enumerate() {
        for pat in &sanitizer_patterns {
            if line.contains(pat) {
                nodes.push(DataflowNode {
                    kind: "sanitizer".to_string(),
                    expression: line.trim().to_string(),
                    file: String::new(),
                    line: i + 1,
                });
                break;
            }
        }
    }
    nodes.truncate(10);
    nodes
}

fn find_sinks(lines: &[&str], lang: &str, _file_path: &PathBuf) -> Vec<DataflowNode> {
    let sink_patterns: Vec<&str> = match lang {
        "Python" => vec![
            "execute(", "os.system(", "subprocess.", "eval(",
            "exec(", "open(", "send(", "render_template_string(",
            "cursor.execute(", "popen(",
        ],
        "JavaScript" | "TypeScript" => vec![
            "eval(", "exec(", "innerHTML", "document.write(",
            "child_process", "fs.readFile(", ".query(",
            "res.send(", "res.write(",
        ],
        "Java" => vec![
            "executeQuery(", "execute(", "Runtime.exec(",
            "ProcessBuilder", "sendRedirect(",
            "getWriter().print(", "setAttribute(",
        ],
        "Go" => vec![
            "exec.Command(", "db.Query(", "db.Exec(",
            "template.HTML(", "http.Redirect(",
            "fmt.Fprintf(w,",
        ],
        _ => vec!["execute", "exec", "eval", "system", "query"],
    };

    let mut nodes = Vec::new();
    for (i, line) in lines.iter().enumerate() {
        for pat in &sink_patterns {
            if line.contains(pat) {
                nodes.push(DataflowNode {
                    kind: "sink".to_string(),
                    expression: line.trim().to_string(),
                    file: String::new(),
                    line: i + 1,
                });
                break;
            }
        }
    }
    nodes.truncate(10);
    nodes
}

fn build_taint_path(
    sources: &[DataflowNode],
    sanitizers: &[DataflowNode],
    sinks: &[DataflowNode],
) -> Vec<String> {
    let mut path = Vec::new();

    if let Some(src) = sources.first() {
        path.push(format!("[SOURCE L{}] {}", src.line, src.expression));
    }

    for san in sanitizers {
        path.push(format!("[SANITIZER L{}] {}", san.line, san.expression));
    }

    if let Some(sink) = sinks.first() {
        path.push(format!("[SINK L{}] {}", sink.line, sink.expression));
    }

    path
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strategy_from_rule_id() {
        assert!(matches!(AnalysisStrategy::from_rule_id("SEC001"), AnalysisStrategy::SecretTriage));
        assert!(matches!(AnalysisStrategy::from_rule_id("VULN003"), AnalysisStrategy::VulnDeepDive));
        assert!(matches!(AnalysisStrategy::from_rule_id("TAINT001"), AnalysisStrategy::TaintTrace));
    }

    #[test]
    fn test_secret_needs_fewer_agents() {
        let strategy = AnalysisStrategy::SecretTriage;
        assert_eq!(strategy.required_agents().len(), 2);
    }

    #[test]
    fn test_vuln_needs_all_agents() {
        let strategy = AnalysisStrategy::VulnDeepDive;
        assert_eq!(strategy.required_agents().len(), 4);
    }

    #[test]
    fn test_find_python_sources() {
        let lines = vec![
            "from flask import request",
            "name = request.args.get('name')",
            "print(name)",
        ];
        let sources = find_sources(&lines, "Python");
        assert!(!sources.is_empty());
        assert_eq!(sources[0].line, 2);
    }

    #[test]
    fn test_find_sanitizers() {
        let lines = vec![
            "from markupsafe import escape",
            "safe = escape(user_input)",
        ];
        let sanitizers = find_sanitizers(&lines, "Python");
        assert!(!sanitizers.is_empty());
    }

    #[test]
    fn test_find_sinks() {
        let lines = vec![
            "cursor.execute(query)",
            "os.system(cmd)",
        ];
        let sinks = find_sinks(&lines, "Python", &PathBuf::from("test.py"));
        assert_eq!(sinks.len(), 2);
    }

    #[test]
    fn test_taint_path_construction() {
        let sources = vec![DataflowNode {
            kind: "source".to_string(),
            expression: "request.args.get('id')".to_string(),
            file: String::new(),
            line: 5,
        }];
        let sanitizers = vec![];
        let sinks = vec![DataflowNode {
            kind: "sink".to_string(),
            expression: "cursor.execute(q)".to_string(),
            file: String::new(),
            line: 10,
        }];

        let path = build_taint_path(&sources, &sanitizers, &sinks);
        assert_eq!(path.len(), 2);
        assert!(path[0].contains("SOURCE"));
        assert!(path[1].contains("SINK"));
    }

    #[test]
    fn test_is_test_file_detection() {
        let finding = Finding {
            rule_id: "SEC001".to_string(),
            severity: crate::scanner::Severity::High,
            title: "test".to_string(),
            description: "test".to_string(),
            file_path: PathBuf::from("tests/fixtures/test_secret.py"),
            line_number: 1,
            line_content: "key = 'abc'".to_string(),
            matched_text: "abc".to_string(),
            suggestion: "remove".to_string(),
        };

        let contents = HashMap::from([(
            PathBuf::from("tests/fixtures/test_secret.py"),
            "key = 'abc'\n".to_string(),
        )]);

        let ctx = gather_static_context(&finding, &contents);
        assert!(ctx.is_test_file);
    }
}
